### PR TITLE
Allow user to set a theme colour for their show

### PR DESCRIPTION
**Pull request by GKFX**
Should add a bit of visual interest to show pages, as not every show needs to be orange! I imagine there will be some shows that take more advantage of this than others—something like *Legally Blonde* almost has to be pink, whereas there are other shows which might not choose a colour at all. The whole thing is implemented with CSS variables, which makes it relatively simple to do something like this, at the cost of Internet Explorer users not seeing much of the effect.

### CODE REVIEW

**Comment by GKFX** [comment]
Near-white colours: the L slider deliberately only goes up to 80% as a hint, but perhaps stronger constraints are required. Will put something in `wcag_colors`.

Inline CSS: yes we use inline CSS quite a bit (31 `style=` and 6 `<style>` in a quick grep) and I don't have immediate plans to remove it. In the far-distant future (CSS3/4 but currently unimplemented in all browsers)  I believe the rule 
```css
[data-custom-color] {
   --custom-color: attr(data-custom-color color, var(--custom-color));
}
```
will allow something like this to be done purely with data attributes, but at the moment either dynamic CSS or Javascript is required, and I'd rather have a pure CSS solution since that avoids a flash of orange before the script kicks in.

No particular reason not to apply it to orgs as well, just wanted to get started on shows as a trial run. I'd hope not to undermine the orange branding that's become so well-known as the homepage will remain orange, as will the footer, admin panels, and basically all shows posted prior to this year. (Personally, I like the orange as a brand colour. If a drama website can't have a loud colour scheme, what can? However, shows are arguably their own brand which is important too.)

**Comment by philosophicles** [comment]
Couple of observations: 

* If there are concerns about how (much) this will be used, we could describe it as a trial when we release it (on twitter and release notes) and reserve the right to back it out in the future? 

* V1 Camdram didn't even have a single consistent brand design: it was essentially skinnable with summer (cows in fields) and winter (snowflakes) themes that ran for ~6 months each, and occasionally IIRC random other themes up for a while according to admins' whims. Eventually that all got replaced with a single more gunmetal-grey design when search-as-you-type was introduced (arguably, that was Camdram V1.5), which lasted at least a whole student generation (probably more) before V2 came. **All of which is to say**: I personally think it's OK to change the brand over time, or to have aspects that are at most loosely-conforming to the brand.

**Comment by GKFX** [comment]
@CHTJonas I think I've covered everything you mentioned. Any further thoughts? When I brought this up in conversation at the ADC there was some interest in being able to colour people pages, but I'd rather not, at least until more people have access to their profiles.

**Comment by CHTJonas** [comment]
Looking good! One thing I did notice is that if you set the colour to `#ffffff` then in the public view the Camdram logo looks okay but when you click through to edit the show then the logo background clashes. Considering the audition/advert/multi roles pages are also all orange maybe the edit page should be too?

**Comment by GKFX** [comment]
That should cover everything now; I've rebased to master and will push once the CI passes.

**Pull request merged**
