### PR TITLE
Role pages

### PR DESCRIPTION
**Pull request by hoyes**
https://role-pages.dev.camdram.net/positions

### CODE REVIEW

**Review by CHTJonas — CHANGES_REQUESTED** [review]
Looks great Pete! 🎉 I haven't looked over the PHP in detail bit did have a quick play in my browser (Firefox). The "View in the CUADC Wiki [edit]" `<div>` seems to be out of place so I had a fiddle around in the console and managed to get something that I think is a little better that reuses the existing `split-header` class.

**Comment by GKFX** [comment]
Yep looks good to me - have made a commit as I don't think I can edit images in a GH code review.

**Comment by GKFX** [comment]
@CHTJonas I have merged in your changes; by setting the margin to `auto 0.5em -1.3em auto` it was possibly to make it look like Peter's original design but without the risk of the widget overlapping the h3 or needing to move the text.

**Review by GKFX — APPROVED** [review]

**Comment by CHTJonas** [comment]
@GKFX thanks! I'm a little confused about the negative margin - for me it makes the view/edit box overlap rather strangely with the text container which I thought was a bug? Unless that's an intentional design choice of course!

Screenshot_2020-12-11 Role Chief Electrician - Camdram

**Comment by GKFX** [comment]
@CHTJonas I thought it was deliberate - the widget was originally floating within the box and pushed up a little bit so text would wrap around it, but not far enough that it would rise fully out. Personally I think it looks nice and sort of attaches the edit widget to the main content box without having to push text aside.

**Comment by hoyes** [comment]
The intent was to have the view/edit box overlapping a bit, but I only tested in Firefox so no wonder it was inconsistent. LGTM now.

**Pull request merged**
