### PR TITLE
Diary refactor

### PR DESCRIPTION
**Pull request by hoyes**
https://diary-refactor.dev.camdram.net/diary.json
https://diary-refactor.dev.camdram.net/diary.xml
https://diary-refactor.dev.camdram.net/diary.ics

https://diary-refactor.dev.camdram.net/societies/society-3/diary.json
https://diary-refactor.dev.camdram.net/societies/society-3/diary.xml
https://diary-refactor.dev.camdram.net/societies/society-3/diary.ics

https://diary-refactor.dev.camdram.net/venues/theatre-royal-drury-lane/diary.json
https://diary-refactor.dev.camdram.net/venues/theatre-royal-drury-lane/diary.xml
https://diary-refactor.dev.camdram.net/venues/theatre-royal-drury-lane/diary.ics

https://diary-refactor.dev.camdram.net/vacancies/auditions/diary.json
https://diary-refactor.dev.camdram.net/vacancies/auditions/diary.xml
https://diary-refactor.dev.camdram.net/vacancies/auditions/diary.ics

@CHTJonas' diary RSS feed link wasn't really working so I've removed it. Is there a use case for a diary RSS feeds though?

Getting a bit pernickety, but I don't really like how start/end times are formatted at the moment:
```
"date": "2018-11-30T00:00:00+00:00",
"start_time": "1970-01-01T12:30:00+00:00",
"end_time": "1970-01-01T16:30:00+00:00",
```

Wondering about changing it everywhere to something like
```
"start_at": "2018-11-30T12:30:00+00:00",
"end_at": "2018-11-30T16:30:00+00:00",
"repeat_until": "2018-12-04T12:30:00",
```
, with "end_at" and "repeat_until" being optional. Means that for performances (which don't have an end time), "end_at" will be absent, and for auditions (which don't repeat) "repeat_until" will be absent. It also mirrors how iCal / RFC 5545 works.

### CODE REVIEW

**Comment by CHTJonas** [comment]
Whoops my mistake didn't check to see if the RSS reader actually returned anything sensible! Yes all looks good to me.

To be honest I think iCal subscriptions are of much more use to people these days than RSS feeds. Only other thing I can think of is that it might be useful to implement some kind of plain text view of the diary for people to copy/paste into emails and alike but I think that may be going a bit OTT.

**Comment by CHTJonas** [comment]
Just testing/comparing https://www.camdram.net/societies/cambridge-university-amateur-dramatic-club/diary/2018/christmas-vacation.json which doesn't seem to work in the same way as the main https://www.camdram.net/diary/2018/christmas-vacation.json endpoint. Is this intentional?

**Comment by hoyes** [comment]
Interesting. Never implemented, but seems obvious now you mention it.

Would ideally involve taking all the other endpoints in [DiaryController](/camdram/camdram/blob/master/src/Acts/CamdramBundle/Controller/DiaryController.php) and making it more generic somehow. Might involve turning everything into query params.

**Comment by CHTJonas** [comment]
Don't think it's a priority tbh. And yeah I think query patterns to `/diary.json` would be nicer that eg. `/diary/2018/summer-vacation.json`.

**Pull request merged**
