### PR TITLE
Date format

### PR DESCRIPTION
**Pull request by hoyes**
* Switched to `start_at`, `end_at` and `repeat_until` fields
 * Added `date_string` for the common use case
 * Standardise on 24-hour time format (there was a 12/24 mix before)
 * Better timezone handling

https://date-format.dev.camdram.net/diary.json
https://date-format.dev.camdram.net/vacancies/auditions/diary.json

Note that during BST, the date/time fields are in UTC but the `date_string` is converted to the local time (e.g. https://date-format.dev.camdram.net/shows/2018-mame.json). I considered making the other fields show a `+1` timezone where appropriate but Symfony doesn't make it easier to override the timezone during serialisation and the Internet seems to suggest always using UTC in APIs. In the JS console, `new Date('2018-06-19T19:30:00+00:00').getHours()` shows '20', so I think anything that can parse ISO 8601 dates will behave sensibly.

Created wiki page with some learnings about timezone handling...: https://github.com/camdram/camdram/wiki/Date-time-handling

### CODE REVIEW

**Comment by hoyes** [comment]
Still a bit of a WIP (probably created the PR prematurely). Currently in a bit of a timezone black hole...

**Comment by CHTJonas** [comment]
Yeah looking good! Might be an idea to create aliases for `start_date`, `end_date` and `time` that we deprecate and then remove in a later breaking change (above project created to track).

**Comment by hoyes** [comment]
I'm happy with this now. I've added back start_date, end_date and time for compatibility. 

I have a feeling application and techie adverts might be expiring an hour too soon in the summer... if so it's been like that forever and I've been working on a vacancies refactor so that should take care of it before the clocks change again so haven't touched that here.

**Comment by CHTJonas** [comment]
Possibly relevant support ticket: https://support.camdram.net/tickets/1304

**Comment by hoyes** [comment]
Almost certainly relevant... only thing I can fathom off the top of my head though would be if the deadline is in April or something. I'll take a look at the weekend.

**Pull request merged**
