### PR TITLE
Added "what is suitable for Camdram" FAQ #343

### PR DESCRIPTION
**Pull request by philosophicles**
Potentially controversial so open for discussion and group revision

### CODE REVIEW

**Comment by hoyes** [comment]
Oops...I accidentally merged more than I intended to into this pull request branch to fix the build... it'll all come out in the wash when it's merged...

**Comment by hoyes** [comment]
I think the comments are good.

I wonder whether we should address the question of "show dates" directly. We could say that we hope to make it easier to add relevant adverts for "non-shows" on Camdram, but for now that films and other things should just create a "show" will something sensible in the date fields (e.g. filming or screening dates).

**Comment by philosophicles** [comment]
Done that @hoyes. Suggest we leave this request open for a week or so in case others want to input, then merge.

**Comment by philosophicles** [comment]
@hoyes Since there's been no further comments, I think we should merge in this additional FAQ point now; I know you've fixed the Travis problems but I can't quite work out how to make GitHub trust this (essentially trivial) pull request...?

**Comment by hoyes** [comment]
Oops I managed to mess this up - yep will merge this in now

**Comment by hoyes** [comment]
Closing this in favour of #350

**Pull request closed without merging**
