### PR TITLE
Correct application div-id directing

### PR DESCRIPTION
**Pull request by dstansby**
I think I changed the div-id to be the slug when I did all the RSS feeds - this should jump down the page correctly now.

### CODE REVIEW

**Comment by dstansby** [comment]
Woops, just fixing this (and making it work for auditions/adverts/applications too)

**Comment by hoyes** [comment]
Shouldn't it route to the 'get_techie' and 'get_application' link, rather than get_show (given that the show pages don't really give 'more details'), a bit like https://github.com/camdram/camdram/blob/master/src/Acts/CamdramBundle/Resources/views/Organisation/vacancies.html.twig ?

**Comment by dstansby** [comment]
Hmm, I seem to remember it working when I tested it - I'll close this request though, revert my changes, work out what was wrong again, and hopefully fix it again...

**Comment by dstansby** [comment]
Okay, turns out I was actually trying to solve the problem you solved 8 days ago (lesson: check for fixes that haven't made it to the live site yet...)

It doesn't seem to be fixed in vacancies.html.twig, but I'm not terribly sure that page exists (http://www.camdram.net/vacancies doesn't work)

**Comment by hoyes** [comment]
Ah sorry yes, that would be have been a useful thing to mention in hindsight...

At work still, but I think the template you've edited is the one for the vacancies section on the home page. I only noticed and fixed the links on show and society/venue pages

**Comment by dstansby** [comment]
Should have fixed it in #316

**Pull request closed without merging**
