### PR TITLE
Remove everything to do with passwords #394

### PR DESCRIPTION
**Pull request by hoyes**
I reckon the time is right for this (see https://github.com/camdram/camdram/issues/394#issuecomment-445495004). Deleting code is very satisfying!

I've tried to leave helpful comments wherever there was previously a login form. Feel free to commit wording tweaks etc.

### CODE REVIEW

**Comment by CHTJonas** [comment]
Looks good to me. Would ideally contact the users who will be affected/lose PW access bearing in mind it's just a handful.

**Comment by philosophicles** [comment]
I agree with @CHTJonas about contacting the (10 or 7?) users affected - but have no problem with going ahead with this in general.

**Comment by hoyes** [comment]
Going to open a support ticket to each of the 10 people referred to in #394 before merging this in.

Want to include a deadline though... will go for 12th Jan (just before term starts again) if no objections...

**Comment by CHTJonas** [comment]
Are we still on track for this merge's deadline? Should probably do a notice on social media etc. DId we get any replies to those 10 support tickets?

**Comment by hoyes** [comment]
I dropped the ball on this. I started sending e-mails before Christmas but only sent 2... Didn't receive any response to those two.

Tempted to make it 19th Jan now (next weekend) whatever happens, and I'll send the remaining e-mails to the others tomorrow or Tuesday.

**Comment by hoyes** [comment]
I've just (belatedly) sent emails to the 4 users who used password login in the last 6 months and rebased this PR. If no objections, I'll give it another week or so then merge it in.

**Comment by CHTJonas** [comment]
Sounds good @hoyes! Might also be worth doing a post on Camdram's various social media platforms just for good measure?

**Pull request merged**
